package domain;
// Generated Nov 10, 2018 9:31:56 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ctdonhang generated by hbm2java
 */
@Entity
@Table(name="ctdonhang"
    ,catalog="web_laptop1"
)
public class Ctdonhang  implements java.io.Serializable {


     private Integer mactdh;
     private Donhang donhang;
     private Sanpham sanpham;
     private int soluong;
     private double gia;
     private double sotien;

    public Ctdonhang() {
    }

	
    public Ctdonhang(Donhang donhang, int soluong, double gia, double sotien) {
        this.donhang = donhang;
        this.soluong = soluong;
        this.gia = gia;
        this.sotien = sotien;
    }
    public Ctdonhang(Donhang donhang, Sanpham sanpham, int soluong, double gia) {
       this.donhang = donhang;
       this.sanpham = sanpham;
       this.soluong = soluong;
       this.gia = gia;
       this.sotien=gia*soluong;
       
    }
    public Ctdonhang(Donhang donhang, Sanpham sanpham, int soluong, double gia, double sotien) {
       this.donhang = donhang;
       this.sanpham = sanpham;
       this.soluong = soluong;
       this.gia = gia;
       this.sotien = sotien;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mactdh", unique=true, nullable=false)
    public Integer getMactdh() {
        return this.mactdh;
    }
    
    public void setMactdh(Integer mactdh) {
        this.mactdh = mactdh;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="madh", nullable=false)
    public Donhang getDonhang() {
        return this.donhang;
    }
    
    public void setDonhang(Donhang donhang) {
        this.donhang = donhang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="masanpham")
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }

    
    @Column(name="soluong", nullable=false)
    public int getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(int soluong) {
        this.soluong = soluong;
    }

    
    @Column(name="gia", nullable=false, precision=22, scale=0)
    public double getGia() {
        return this.gia;
    }
    
    public void setGia(double gia) {
        this.gia = gia;
    }

    
    @Column(name="sotien", nullable=false, precision=22, scale=0)
    public double getSotien() {
        return this.sotien;
    }
    
    public void setSotien(double sotien) {
        this.sotien = sotien;
    }
}