package domain;
// Generated Apr 7, 2019 10:23:46 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Donhang generated by hbm2java
 */
public class Donhang  implements java.io.Serializable {


     private Integer madh;
     private Khachhang khachhang;
     private String tenkhachhang;
     private Date ngaydh;
     private String diachi;
     private String sdt;
     private String email;
     private double tongtien;
     private Date ngaygiao;
     private int tinhtrang;
     private Set<Ctdonhang> ctdonhangs = new HashSet<Ctdonhang>(0);

    public Donhang() {
    }

	
    public Donhang(Khachhang khachhang, String tenkhachhang, Date ngaydh, String diachi, String sdt, String email, double tongtien, int tinhtrang) {
        this.khachhang = khachhang;
        this.tenkhachhang = tenkhachhang;
        this.ngaydh = ngaydh;
        this.diachi = diachi;
        this.sdt = sdt;
        this.email = email;
        this.tongtien = tongtien;
        this.tinhtrang = tinhtrang;
    }
    public Donhang(Khachhang khachhang, String tenkhachhang, Date ngaydh, String diachi, String sdt, String email, double tongtien, Date ngaygiao, int tinhtrang, Set<Ctdonhang> ctdonhangs) {
       this.khachhang = khachhang;
       this.tenkhachhang = tenkhachhang;
       this.ngaydh = ngaydh;
       this.diachi = diachi;
       this.sdt = sdt;
       this.email = email;
       this.tongtien = tongtien;
       this.ngaygiao = ngaygiao;
       this.tinhtrang = tinhtrang;
       this.ctdonhangs = ctdonhangs;
    }
   
    public Integer getMadh() {
        return this.madh;
    }
    
    public void setMadh(Integer madh) {
        this.madh = madh;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public String getTenkhachhang() {
        return this.tenkhachhang;
    }
    
    public void setTenkhachhang(String tenkhachhang) {
        this.tenkhachhang = tenkhachhang;
    }
    public Date getNgaydh() {
        return this.ngaydh;
    }
    
    public void setNgaydh(Date ngaydh) {
        this.ngaydh = ngaydh;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public double getTongtien() {
        return this.tongtien;
    }
    
    public void setTongtien(double tongtien) {
        this.tongtien = tongtien;
    }
    public Date getNgaygiao() {
        return this.ngaygiao;
    }
    
    public void setNgaygiao(Date ngaygiao) {
        this.ngaygiao = ngaygiao;
    }
    public int getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(int tinhtrang) {
        this.tinhtrang = tinhtrang;
    }
    public Set<Ctdonhang> getCtdonhangs() {
        return this.ctdonhangs;
    }
    
    public void setCtdonhangs(Set<Ctdonhang> ctdonhangs) {
        this.ctdonhangs = ctdonhangs;
    }




}


