package domain;
// Generated Apr 7, 2019 10:23:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nhasanxuat generated by hbm2java
 */
public class Nhasanxuat  implements java.io.Serializable {


     private Integer mansx;
     private String tennsx;
     private String hinhanh;
     private Set<Sanpham> sanphams = new HashSet<Sanpham>(0);

    public Nhasanxuat() {
    }

	
    public Nhasanxuat(String tennsx, String hinhanh) {
        this.tennsx = tennsx;
        this.hinhanh = hinhanh;
    }
    public Nhasanxuat(String tennsx, String hinhanh, Set<Sanpham> sanphams) {
       this.tennsx = tennsx;
       this.hinhanh = hinhanh;
       this.sanphams = sanphams;
    }
   
    public Integer getMansx() {
        return this.mansx;
    }
    
    public void setMansx(Integer mansx) {
        this.mansx = mansx;
    }
    public String getTennsx() {
        return this.tennsx;
    }
    
    public void setTennsx(String tennsx) {
        this.tennsx = tennsx;
    }
    public String getHinhanh() {
        return this.hinhanh;
    }
    
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }
    public Set<Sanpham> getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set<Sanpham> sanphams) {
        this.sanphams = sanphams;
    }




}


