package domain;
// Generated Apr 7, 2019 10:23:46 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Thongtindichvu generated by hbm2java
 */
public class Thongtindichvu  implements java.io.Serializable {


     private Integer matt;
     private String tentt;
     private String noidung;
     private String hinhanh;
     private Date ngaydang;

    public Thongtindichvu() {
    }

	
    public Thongtindichvu(String tentt, String noidung, String hinhanh) {
        this.tentt = tentt;
        this.noidung = noidung;
        this.hinhanh = hinhanh;
    }
    public Thongtindichvu(String tentt, String noidung, String hinhanh, Date ngaydang) {
       this.tentt = tentt;
       this.noidung = noidung;
       this.hinhanh = hinhanh;
       this.ngaydang = ngaydang;
    }
   
    public Integer getMatt() {
        return this.matt;
    }
    
    public void setMatt(Integer matt) {
        this.matt = matt;
    }
    public String getTentt() {
        return this.tentt;
    }
    
    public void setTentt(String tentt) {
        this.tentt = tentt;
    }
    public String getNoidung() {
        return this.noidung;
    }
    
    public void setNoidung(String noidung) {
        this.noidung = noidung;
    }
    public String getHinhanh() {
        return this.hinhanh;
    }
    
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }
    public Date getNgaydang() {
        return this.ngaydang;
    }
    
    public void setNgaydang(Date ngaydang) {
        this.ngaydang = ngaydang;
    }




}


