package domain;
// Generated Apr 7, 2019 10:23:46 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String tendangnhap;
     private String matkhau;
     private String quyen;

    public User() {
    }

    public User(String tendangnhap, String matkhau, String quyen) {
       this.tendangnhap = tendangnhap;
       this.matkhau = matkhau;
       this.quyen = quyen;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTendangnhap() {
        return this.tendangnhap;
    }
    
    public void setTendangnhap(String tendangnhap) {
        this.tendangnhap = tendangnhap;
    }
    public String getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }
    public String getQuyen() {
        return this.quyen;
    }
    
    public void setQuyen(String quyen) {
        this.quyen = quyen;
    }




}


